# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
#orbs:
  #coveralls: coveralls/coveralls@2.1.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/GoonMart-Online-Store
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: |
            CI=false npm run build 
            #&& npm run test -- --coverage

      #- coveralls/upload:
        #  path: ./coverage/lcov.info
        #  token: $COVERALLS_REPO_TOKEN

      - store_artifacts:
          path: build
