# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
#orbs:
  #coveralls: coveralls/coveralls@2.1.1

orbs:
  codecov: codecov/codecov@3.2.3
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/GoonMart-Online-Store
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: |
            CI=false npm run build 
            #&& npm run test -- --coverage

      # test the code
  - run:
      name: Run tests
      command: npm run test
      post-steps:
        - store_artifacts:
          path: coverage
        - codecov/upload:
          file: coverage/coverage-final.json
        - store_artifacts:
          path: build
        - node/test:
          post-steps:
            - codecov/upload

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)


      #- coveralls/upload:
        #  path: ./coverage/lcov.info
        #  token: $COVERALLS_REPO_TOKEN
    # commands:
    #   store-coverage-data:
    #     steps:
    #       
    #   upload-coverage:
    #     steps:
    #       
